package vistas;



import control.Conexion;
import data.MateriaData;
import java.sql.Connection;
import java.util.ArrayList;
import modelo.Materia;
import java.util.HashSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pali
 */
public class Formulario_materias extends javax.swing.JInternalFrame {
private HashSet<Materia> todasLasMaterias;
private MateriaData materiaData = null;

Conexion conexion = new Conexion();          
//Connection con = conexion.getConexion(); 

    /**
     * Creates new form Formulario_materias
     */
    public Formulario_materias(Conexion conexion) {
        initComponents();
         setTitle("Registrar nueva Materia");  
        this.materiaData = new MateriaData(conexion);        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtMateria = new javax.swing.JTextField();
        jtID = new javax.swing.JTextField();
        jtAnio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jB_Guardar = new javax.swing.JButton();
        jB_nuevo = new javax.swing.JButton();
        jB_Salir = new javax.swing.JButton();
        jB_buscar = new javax.swing.JButton();
        jCEstado = new javax.swing.JCheckBox();
        jB_Actualizar1 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 400));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel3.setText("Año");

        jtMateria.setText("Inserte su nombre de la materia");
        jtMateria.setToolTipText("");
        jtMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMateriaActionPerformed(evt);
            }
        });

        jtID.setText("Inserte el ID");

        jtAnio.setText("Inserte el año");

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel4.setText("Formulario de materias ");

        jB_Guardar.setBackground(new java.awt.Color(204, 204, 204));
        jB_Guardar.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jB_Guardar.setText("Guardar");
        jB_Guardar.setPreferredSize(new java.awt.Dimension(80, 30));
        jB_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GuardarActionPerformed(evt);
            }
        });

        jB_nuevo.setBackground(new java.awt.Color(204, 204, 204));
        jB_nuevo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jB_nuevo.setText("Nuevo");
        jB_nuevo.setEnabled(false);
        jB_nuevo.setPreferredSize(new java.awt.Dimension(80, 30));
        jB_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_nuevoActionPerformed(evt);
            }
        });

        jB_Salir.setBackground(new java.awt.Color(204, 204, 204));
        jB_Salir.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jB_Salir.setText("Salir");
        jB_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SalirActionPerformed(evt);
            }
        });

        jB_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_find_lupa_21889.png"))); // NOI18N
        jB_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarActionPerformed(evt);
            }
        });

        jCEstado.setText("Activa");

        jB_Actualizar1.setBackground(new java.awt.Color(204, 204, 204));
        jB_Actualizar1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jB_Actualizar1.setText("Actualizar");
        jB_Actualizar1.setEnabled(false);
        jB_Actualizar1.setPreferredSize(new java.awt.Dimension(80, 30));
        jB_Actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Actualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jB_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jB_Actualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jB_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248)
                        .addComponent(jB_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(jtAnio)
                            .addComponent(jCEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jB_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jCEstado)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Actualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMateriaActionPerformed

    private void jB_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GuardarActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(jtID.getText());
        String nombre=jtMateria.getText();
        int anio=Integer.parseInt(jtAnio.getText());
        boolean activa = jCEstado.isSelected();
       MateriaData md = new MateriaData(conexion); 
       Materia materia =new Materia(nombre, anio, activa);
       // todasLasMaterias.add(nm);
       if(md.agregarMateria(materia)){
           JOptionPane.showMessageDialog(this,"Materia Agregada con éxito");
           jtID.setText(materia.getIdMateria()+"");
           jB_nuevo.setEnabled(true);
       }
       
    }//GEN-LAST:event_jB_GuardarActionPerformed

    private void jB_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SalirActionPerformed
        // TODO add your handling code here:
     dispose();   
    }//GEN-LAST:event_jB_SalirActionPerformed

    private void jB_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarActionPerformed
        // TODO add your handling code here:              // falta agregar un try para evitar buscar "" vacios
        int leg=-1;
        try {
            leg=Integer.parseInt(jtID.getText());
            MateriaData md = new MateriaData(conexion);
           
            Materia materia = md.obtenerMateriaXId(leg);
            if(materia != null){

                jtMateria.setText(materia.getNombre());
                jtAnio.setText(materia.getAnio()+"");                
                jCEstado.setSelected(materia.isActivo());
                jB_nuevo.setEnabled(true);
                jB_Actualizar1.setEnabled(true);
                jB_Guardar.setEnabled(false);                

            }else{
                JOptionPane.showMessageDialog(this,"No existe una Materia con ese Código");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Código Inválido ");
        }

    }//GEN-LAST:event_jB_buscarActionPerformed

    private void jB_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_nuevoActionPerformed
        // TODO add your handling code here:
        this.jtMateria.setText("");
        this.jtAnio.setText("");
        this.jCEstado.setSelected(true);
        jB_Guardar.setEnabled(true);
        jB_nuevo.setEnabled(false);        
        jB_Actualizar1.setEnabled(false); 
    }//GEN-LAST:event_jB_nuevoActionPerformed

    private void jB_Actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Actualizar1ActionPerformed
        // TODO add your handling code here:
          int id=-1;
        try {
            id= Integer.parseInt(jtID.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Usted debe ingresar un número");
            jtID.requestFocus();
        }
        String nom=jtMateria.getText();
        int anio =-1;
        try{
            anio =Integer.parseInt(jtAnio.getText());
        }catch(Exception ex){

            JOptionPane.showMessageDialog(this, "Usted debe ingresar un número");
            jtAnio.requestFocus();
        }

        boolean estado = jCEstado.isSelected();

        Materia materia = new Materia(id, nom, anio, estado);
        if(materiaData.modificarMateria(materia)){
            JOptionPane.showMessageDialog(this,"Materia Modificado con éxito");
        }
        
    }//GEN-LAST:event_jB_Actualizar1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Actualizar1;
    private javax.swing.JButton jB_Guardar;
    private javax.swing.JButton jB_Salir;
    private javax.swing.JButton jB_buscar;
    private javax.swing.JButton jB_nuevo;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtAnio;
    private javax.swing.JTextField jtID;
    private javax.swing.JTextField jtMateria;
    // End of variables declaration//GEN-END:variables

}
