/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */


package vistas;


import java.sql.*;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import data.MateriaData;

import modelo.Alumno;
import modelo.Colegio;
import modelo.Materia;

import control.Conexion;

/**
 *
 * @author saimon
 */
public class Form_Inscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_Inscripcion
     * 
     */
    
    Colegio gt;
    // DefaultTableModel model = new DefaultTableModel();
    private DefaultTableModel modelo;
            
    public Form_Inscripcion(HashSet<Alumno> todosLosAlumnos, HashSet<Materia> todasLasMaterias) {
        
        initComponents();
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        

                
        modelo = new DefaultTableModel();
        
        armarCabecera();
        llenarTabla();
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /*
        
        try {
           // PreparedStatement pst = gt.prepareStatement("select idAlumno, nombre, apellido, materia");
           // ResultSet rs = pst.executeQuery();
           
            Conexion conexion = new Conexion(); 
            Connection cn = conexion.getConexion();
            MateriaData md = new MateriaData(conexion);
            List<Materia> lista_materias = md.obtenerMaterias();
            
            
            JTable table  = new JTable(data, columnNames);
            // jTable_alumnos.setValueAt(lista_materias,1,1);
            System.out.println("2222" + data);
           
            
        } catch (Exception e) {
            System.out.println("3333333333" + e);
        }
        */
        
    }

    
    
    
    
    
    @Override
    public String toString() {
        return "Form_Inscripcion{" + "jTab_alumno=" +  table + '}';
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Inscripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jL_Alumno = new javax.swing.JLabel();
        jCbox_dato = new javax.swing.JComboBox<>();
        jBut_inscribir = new javax.swing.JButton();
        jBut_Anular = new javax.swing.JButton();
        jBut_salir = new javax.swing.JButton();
        jL_listadoMaterias = new javax.swing.JLabel();
        jRadBut_inscripas = new javax.swing.JRadioButton();
        jRadBut_No_Inscscripta = new javax.swing.JRadioButton();
        jLabelfondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(750, 750));

        jL_Inscripcion.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jL_Inscripcion.setText("Formulario de Inscripción");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código Id", "Materia", "Año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setHeaderValue("Código Id");
            table.getColumnModel().getColumn(1).setHeaderValue("Materia");
            table.getColumnModel().getColumn(2).setHeaderValue("Año");
        }

        jL_Alumno.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jL_Alumno.setText("Alumno");

        jCbox_dato.setToolTipText("");

        jBut_inscribir.setBackground(new java.awt.Color(204, 204, 204));
        jBut_inscribir.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jBut_inscribir.setText("Inscribir");

        jBut_Anular.setBackground(new java.awt.Color(204, 204, 204));
        jBut_Anular.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jBut_Anular.setText("Anular Inscripción ");

        jBut_salir.setBackground(new java.awt.Color(204, 204, 204));
        jBut_salir.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jBut_salir.setText("Salir");

        jL_listadoMaterias.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jL_listadoMaterias.setText("Listado de Materias");

        jRadBut_inscripas.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jRadBut_inscripas.setText("Inscriptas");
        jRadBut_inscripas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBut_inscripasActionPerformed(evt);
            }
        });

        jRadBut_No_Inscscripta.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jRadBut_No_Inscscripta.setText("No Inscriptas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jL_Inscripcion))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jL_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jL_listadoMaterias))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jRadBut_inscripas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jRadBut_No_Inscscripta))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jBut_inscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jBut_Anular, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jCbox_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jBut_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabelfondo, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jL_Inscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jL_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jL_listadoMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadBut_inscripas)
                    .addComponent(jRadBut_No_Inscscripta))
                .addGap(338, 338, 338)
                .addComponent(jBut_inscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jBut_Anular, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jCbox_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jBut_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabelfondo, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadBut_inscripasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBut_inscripasActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jRadBut_inscripasActionPerformed

    
    
    
    
    
    
    
    private void armarCabecera() {                 
    
    
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("Código Id");
        columnas.add("Materiass");
        columnas.add("Año");
       
        
        for(Object it : columnas) {
        modelo.addColumn(it);
        
        }
        table.setModel(modelo);
        
    }         
        








    
private void llenarTabla() {                 
    
            Conexion conexion = new Conexion(); 
            Connection cn = conexion.getConexion();
            
            //probando con mostrar objetos Materia desde DB, tiene que mostrar cursadas
            MateriaData md = new MateriaData(conexion);
            List<Materia> lista_materias = md.obtenerMaterias();
            
            lista_materias.forEach((it) -> {
                modelo.addRow(new Object [] {it.getIdMateria(), it.getNombre(), it.getAnio()});
        });
 
    }    









    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Anular;
    private javax.swing.JButton jBut_inscribir;
    private javax.swing.JButton jBut_salir;
    private javax.swing.JComboBox<String> jCbox_dato;
    private javax.swing.JLabel jL_Alumno;
    private javax.swing.JLabel jL_Inscripcion;
    private javax.swing.JLabel jL_listadoMaterias;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JRadioButton jRadBut_No_Inscscripta;
    private javax.swing.JRadioButton jRadBut_inscripas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
