/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.sql.*;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.util.HashSet;

import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import modelo.Alumno;
import modelo.Colegio;
import modelo.Materia;

/**
 *
 * @author saimon
 */
public class Form_Notas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_Inscripcion
     * 
     */
    
    Colegio gt;
    DefaultTableModel model = new DefaultTableModel();
            
    public Form_Notas(HashSet<Alumno> todosLosAlumnos, HashSet<Materia> todasLasMaterias) {
        initComponents();
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        try {
           // PreparedStatement pst = gt.prepareStatement("select idAlumno, nombre, apellido, materia");
           // ResultSet rs = pst.executeQuery();
            
            jTable_alumnos  = new JTable(model);
           
           
            
        } catch (Exception e) {
        }
        
    }

    @Override
    public String toString() {
        return "Form_Inscripcion{" + "jTab_alumno=" +  jTable_alumnos + '}';
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Inscripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_alumnos = new javax.swing.JTable();
        jL_Alumno = new javax.swing.JLabel();
        jCbox_dato = new javax.swing.JComboBox<>();
        jBut_inscribir = new javax.swing.JButton();
        jBut_salir = new javax.swing.JButton();
        jLabelfondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(750, 650));
        setRequestFocusEnabled(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_Inscripcion.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jL_Inscripcion.setText("Carga de Notas");
        getContentPane().add(jL_Inscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 280, 29));

        jTable_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código Id", "Materia", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_alumnos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 630, 280));

        jL_Alumno.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jL_Alumno.setText("Alumno");
        getContentPane().add(jL_Alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 90, 25));

        jCbox_dato.setToolTipText("");
        getContentPane().add(jCbox_dato, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 157, 25));

        jBut_inscribir.setBackground(new java.awt.Color(204, 204, 204));
        jBut_inscribir.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jBut_inscribir.setText("Guardar nota");
        getContentPane().add(jBut_inscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 190, 55));

        jBut_salir.setBackground(new java.awt.Color(204, 204, 204));
        jBut_salir.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jBut_salir.setText("Salir");
        getContentPane().add(jBut_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 100, 55));
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 699, 606));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_inscribir;
    private javax.swing.JButton jBut_salir;
    private javax.swing.JComboBox<String> jCbox_dato;
    private javax.swing.JLabel jL_Alumno;
    private javax.swing.JLabel jL_Inscripcion;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_alumnos;
    // End of variables declaration//GEN-END:variables
}
