/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.sql.*;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.util.HashSet;

import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import modelo.Alumno;
import modelo.Colegio;
import modelo.Materia;

/**
 *
 * @author saimon
 */
public class Form_Notas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_Inscripcion
     * 
     */
    
    Colegio gt;
    DefaultTableModel model = new DefaultTableModel();
            
    public Form_Notas(HashSet<Alumno> todosLosAlumnos, HashSet<Materia> todasLasMaterias) {
        initComponents();
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        try {
           // PreparedStatement pst = gt.prepareStatement("select idAlumno, nombre, apellido, materia");
           // ResultSet rs = pst.executeQuery();
            
            jTable_alumnos  = new JTable(model);
           
           
            
        } catch (Exception e) {
        }
        
    }

    @Override
    public String toString() {
        return "Form_Inscripcion{" + "jTab_alumno=" +  jTable_alumnos + '}';
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Inscripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_alumnos = new javax.swing.JTable();
        jL_Alumno = new javax.swing.JLabel();
        jCbox_dato = new javax.swing.JComboBox<>();
        jBut_inscribir = new javax.swing.JButton();
        jBut_salir = new javax.swing.JButton();
        jLabelfondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(750, 650));
        setRequestFocusEnabled(false);

        jL_Inscripcion.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jL_Inscripcion.setText("Carga de Notas");

        jTable_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código Id", "Materia", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_alumnos);

        jL_Alumno.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jL_Alumno.setText("Alumno");

        jCbox_dato.setToolTipText("");

        jBut_inscribir.setBackground(new java.awt.Color(204, 204, 204));
        jBut_inscribir.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jBut_inscribir.setText("Guardar nota");

        jBut_salir.setBackground(new java.awt.Color(204, 204, 204));
        jBut_salir.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jBut_salir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jL_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jBut_inscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340)
                .addComponent(jBut_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jL_Inscripcion))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jCbox_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabelfondo, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jL_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBut_inscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBut_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jL_Inscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jCbox_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabelfondo, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_inscribir;
    private javax.swing.JButton jBut_salir;
    private javax.swing.JComboBox<String> jCbox_dato;
    private javax.swing.JLabel jL_Alumno;
    private javax.swing.JLabel jL_Inscripcion;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_alumnos;
    // End of variables declaration//GEN-END:variables
}
